version: '3'

services:
  db:
    image: postgis/postgis:11-2.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simi
      - PGDATA=/var/lib/postgresql/data/pgdata
  await-db:
    image: postgis/postgis:11-2.5-alpine
    command: /var/lib/postgresql/data/await-db/await.sh
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simi
    volumes:
      - "./await-db:/var/lib/postgresql/data/await-db"
  simi:
    image: sogis/simi
    environment:
    - CUBA_DATASOURCE_USERNAME=postgres
    - CUBA_DATASOURCE_PASSWORD=postgres
    - CUBA_DATASOURCE_DBNAME=simi
    - CUBA_DATASOURCE_HOST=db
    - CUBA_DATASOURCE_PORT=5432
    - CUBA_AUTOMATICDATABASEUPDATE=true
    ports:
      - "8080:8080"